# Generated by Django 2.0.5 on 2018-05-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Deadline date'),
        ),
    ]
